add solution for lection3 03-calendar
js-tasks-ru/htmlcss-20241107_bova-s pull request #8
Opened 2024-11-21 09:10 UTC by bova-s

2024-11-21 09:10 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-11-21 09:47 UTC, GSemikozov requested changes

2024-11-21 09:47 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  line-height: 24px;
не хватает паддингов и других свойств описывающих текст

2024-11-21 09:47 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  line-height: 24px;
или тогда line-height не надо

2024-11-21 09:47 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  align-self: center;
лишнее

2024-11-21 09:47 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  align-items: stretch;
это значения по умолчанию, их не обязательно указывать)

2024-11-21 09:47 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__week {
если .calendar__week и calendar__day почти одинаковые, тогда делаем через общий элемент, а специфическое - через модификаторы

2024-11-21 10:15 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-11-21 11:33 UTC, GSemikozov requested changes
надо исправить конфликт

2024-11-21 11:33 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  padding: 28px 30px 40px;
`28 26 32`

2024-11-21 11:33 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  text-align: center;
и margin-bottom: 24px, верно?

2024-11-21 11:33 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  justify-content: center;
здесь же - 
font-style: normal;
  line-height: 24px;
  font-weight: 400;

2024-11-23 14:13 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-11-23 14:14 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-11-23 15:14 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-12-03 13:13 UTC, GSemikozov approved these changes

2024-12-03 13:13 UTC, jsru-1 commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2024-12-03 13:20 UTC, GSemikozov approved these changes

2024-12-03 13:20 UTC, merged